name = "kavinjey"
type = "webpack"
account_id = "10e989a096eecf18d6dd183b0c01f01e"
route = 'kavinjey.xyz/'
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-04-11"

[site]
bucket = "dist"
entry-point = "workers-site"

